//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimplomWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> complete_products_id { get; set; }
        public Nullable<int> tile_id { get; set; }
        public int quantity { get; set; }
        public decimal price_at_moment { get; set; }
    
        public virtual Complete_Products Complete_Products { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Tiles Tiles { get; set; }
    }
}
