//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimplomWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string order_number { get; set; }
        public decimal total_amount { get; set; }
        public string status { get; set; }
        public string delivery_address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
