//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimplomWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiles
    {
        public Tiles()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public decimal price { get; set; }
        public string photo { get; set; }
        public Nullable<int> stone_type_id { get; set; }
        public Nullable<int> tone_id { get; set; }
        public string slab_size { get; set; }
        public Nullable<int> thickness_mm { get; set; }
        public Nullable<int> stock_quantity { get; set; }
    
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual Stone_Types Stone_Types { get; set; }
        public virtual Tones Tones { get; set; }
    }
}
